### PR TITLE
Geomplot additions2

### PR DESCRIPTION
**Pull request by zerothi**
I have rebased, so basically it should work.

However the tests fail... Could you figure out what I did wrong? And fix it in the MR branch? Then I can merge?

### CODE REVIEW

**Comment by pfebrer** [comment]
I didn't see this one, sorry!

**Comment by pfebrer** [comment]
I think the branch is fine now. The images are not in the commit history anymore. Can you check?

**Comment by pfebrer** [comment]
The tests pass for me on my branch. I haven't tried with this PR. Is it possible that you are running the tests in an environment without plotly? Even though I'm trying to decouple the general tests from plotly I haven't fully done it yet :)

**Comment by zerothi** [comment]
> The tests pass for me on my branch. I haven't tried with this PR. Is it possible that you are running the tests in an environment without plotly? Even though I'm trying to decouple the general tests from plotly I haven't fully done it yet :)

No, I tested yours (succeeded) and mine (failed). ;)

**Pull request closed without merging**
