### PR TITLE
maint: upgraded a global environ strategy

### PR DESCRIPTION
**Pull request by zerothi**
A bit more flexible, and also allowed post-processing values

### CODE REVIEW

**Comment by zerothi** [comment]
@pfebrer96 I don't know if you prefer this in the sisl/master, and then do a rebase?

**Comment by pfebrer** [comment]
Yes, it's probably better if you put it on master :)

**Comment by pfebrer** [comment]
Sorry that I didn't see it, I don't receive any mail when you do pull requests (only when you comment) :sweat_smile:

**Comment by pfebrer** [comment]
By the way, could `register_environ_var` also return the value of the variable? Or is there a reason why you didn't do it like this?

**Comment by pfebrer** [comment]
> Yes, it's probably better if you put it on master :)

Nevermind, I can merge it, because I see that you already updated the imports in my files :)

**Comment by zerothi** [comment]
> By the way, could `register_environ_var` also return the value of the variable? Or is there a reason why you didn't do it like this?

I did it like this for clarity, `register_environ_var` does not imply it returns anything. Also, it would aid in the overview in the code if all env-vars are registered one place, and then used subsequently.

**Comment by zerothi** [comment]
> > Yes, it's probably better if you put it on master :)
> 
> Nevermind, I can merge it, because I see that you already updated the imports in my files :)

I am in the process of putting it in master, so hold on ;)

**Comment by zerothi** [comment]
it is in, rebase, and do the minor changes I did here.

**Comment by pfebrer** [comment]
Ok :+1:

**Comment by zerothi** [comment]
@pfebrer96 there was a bug, could you please pull from master again, then rebase! Thanks ;)

**Comment by pfebrer** [comment]
Yeah I had also fixed the same bug in my branch :smile:

**Pull request closed without merging**
